export const PRODUCT_LOADING="PRODUCT_LOADING";
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS";
export const PRODUCT_ERROR= "PRODUCT_ERROR";
export const PRODUCT_FILTER="PRODUCT_FILTER";
export const PRODUCT_SEARCH="PRODUCT_SEARCH";